### ISSUE TITLE
Integrate with metalsmith-collections

### ISSUE THREAD

**Issue by sonniesedge** [metalsmith/default-values#9]
It would extremely useful if the very excellent metalsmith-default-values could utilise collections defined by [metalsmith-collections](https://github.com/segmentio/metalsmith-collections).

At the moment I am writing:

```
    .use(collections({
        posts: {
          pattern: ['posts/*.md', '!posts/index.md'],
          sortBy: 'date',
          reverse: true
        }
    }))
    .use(defaultvals([
        {
            pattern: ['posts/*.md', '!posts/index.md'],
            defaults: {
                layout: 'post.njk'
            }
        }
    ]))
```

This means that I'm matching against posts twice in the build file.

It would be great if I could do something like:

```
    .use(collections({
        posts: {
          pattern: ['posts/*.md', '!posts/index.md'],
          sortBy: 'date',
          reverse: true
        }
    }))
    .use(defaultvals([
        {
            match: { collection: 'posts' }, // Use a previously defined collection here
            defaults: {
                layout: 'post.njk'
            }
        }
    ]))
```

While this might seem unnecessary in this short simple example, it would become more useful in more advanced build chains.

An example of a module using `match` in this way is [metalsmith-permalinks](https://github.com/segmentio/metalsmith-permalinks).

I hope this issue is useful and can inspire further great development! ❤️

**Comment by woodyrew** [comment]
Interesting, I use it early in my build chain to add defaults where they're not set but this is an equally sensible workflow.

On a side note, this would work with collections I believe:
```
.use(defaultvals([
  {
    pattern: ['posts/*.md', '!posts/index.md'],
    defaults: {
      layout: 'post.njk'
      collection: 'posts'
    }
  }
]))
.use(collections({
    posts: {
      sortBy: 'date',
      reverse: true
    }
}))
```

I'll have a look at adding `match` to the functionality. Thanks for the suggestion.

**Comment by webketje** [comment]
Closing since the comment by @woodyrew is a better way to pair collections with default-values
